const movies = [
  {
    adult: false,
    backdrop_path: '/52AfXWuXCHn3UjD17rBruA9f5qb.jpg',
    genre_ids: [Array],
    id: 550,
    original_language: 'en',
    original_title: 'Fight Club',
    overview: 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
    popularity: 55.366,
    poster_path: '/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg',
    release_date: '1999-10-15',
    title: 'Fight Club',
    video: false,
    vote_average: 8.4,
    vote_count: 20727
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [Array],
    id: 722482,
    original_language: 'en',
    original_title: 'Superhero Fight Club 2.0',
    overview: '',
    popularity: 4.17,
    poster_path: '/j2cA1s0OLvSVVbqqHk1a7aZotCy.jpg',
    release_date: '2016-09-29',
    title: 'Superhero Fight Club 2.0',
    video: false,
    vote_average: 7,
    vote_count: 4
  },
  {
    adult: false,
    backdrop_path: '/u0a4CSy73GP11wVPz8hm0tHQwci.jpg',
    genre_ids: [Array],
    id: 466848,
    original_language: 'en',
    original_title: 'Superhero Fight Club',
    overview: "Oliver introduces Barry to his own little fight club which features such members as Roy Harper, Laurel Lance, Malcolm Merlyn and Ra's Al Ghul.",
    popularity: 2.274,
    poster_path: '/zjPn7JUg2tsxlRWp4luK0YVX48Y.jpg',
    release_date: '2015-04-13',
    title: 'Superhero Fight Club',
    video: false,
    vote_average: 7.3,
    vote_count: 25
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [Array],
    id: 51021,
    original_language: 'en',
    original_title: 'Lure: Teen Fight Club',
    overview: "A community is under siege as three Belmont Highschool coed students go missing with no trace of their whereabouts. The pressure is on the police to capture the culprits responsible. Scouring the school hallways in search of clues, undercover female detective Maggie Rawdon (Jessica Sonnerborn) enters Belmont High as a transfer student in an attempt to solve the hideous disappearance of the students. Maggie makes a few new friends, and gets invited to a private rave in the country. Just as the group begins to suspect that they've taken a wrong turn, however, the trap is sprung and Maggie finds out firsthand what fate has befallen the missing girls.",
    popularity: 2.558,
    poster_path: '/ipl6NdM0LwyakzLH9gKBDn8YhmZ.jpg',
    release_date: '2010-11-16',
    title: 'Lure: Teen Fight Club',
    video: false,
    vote_average: 5,
    vote_count: 7
  },
];

module.exports = {
  movies,
};
